---

site_name: "pyPoseidon"
use_directory_urls: false
repo_url: "https://github.com/ec-jrc/pyPoseidon"

theme:
  name: "material"
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"

nav:
  - Overview : index.md
  - Installation : installation.md
  - Structure : structure.md
  - User Guide : 
      - "Meteo": meteo.md
      - "Dem": dem.md
      - "Boundary": boundary.md
      - "Mesh": mesh.md
      - "Model": model.md
      - "Utilities": utils.md
  - API : api.md

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.superfences"
  - toc:
      permalink: true

plugins:
  - "search"
  - "mkdocstrings":
