{% set name = "pyposeidon" %}
{% set version = "0.6.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: {{ build }}

outputs:
  - name: pyposeidon-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
#       - python                                 # [build_platform != target_platform]
#       - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - python
        - pyresample
        - pygeos >=0.10
        - rasterio
        - rioxarray
        - jigsaw
        - cfgrib
        - colorlog
        - f90nml
        - zarr
        - gmsh >=4.8.4
        - python-gmsh
        - tqdm
        - xarray
        - pandas
        - geopandas >=0.10.1
        - numpy
        - psutil
        - requests
        - scipy
        - netCDF4
        - dask
        - shapely =1.7.1
        - pydap >=3.3.0

      test:
        imports:
          - pyposeidon

  - name: pyposeidon
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('pyposeidon-base', exact=True) }}
        - holoviews
        - geoviews
        - hvplot
        - ipympl
        - itkwidgets
        - mayavi
        - matplotlib >=3.3
        - cartopy <=0.20
        - ffmpeg

      test:
        imports:
          - pyposeidon


about:
  home: https://github.com/ec-jrc/pyposeidon
  license: EUPL-1.2
  license_file: LICENSE
  summary: 'Framework for Hydrodynamic simulations'

  # The remaining entries in this section are optional, but recommended.
  description: |
    pyPoseidon is a framework to setup, run and analyse geoflows.
    It warps around several solvers and is using python for the
    pre/post processing utilizing popular packages
    such as xarray, pandas, geopandas etc.
  doc_url: https://pyposeidon.readthedocs.io/
  dev_url: https://github.com/ec-jrc/pyPoseidon

extra:
  recipe-maintainers:
    - brey
    - pmav99
